print("===Resume===")
print("Name : Mohit Gole ")
print("Email : mohitgole999@gmail.com")
print("Skills :")
print( "-Java")
print("-HTML & CSS")
print("-Problem Solving")
print("Experience : 2 years at XYZ Ltd.")
